<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    // protected $with = ['category', 'user'];

    public $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'category_id'
    ];

    // public $guarded = [];


    //to change the default route-model binding key
    //public function getRouteKeyName()
    //{
    // // return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
    // return 'slug';
    //}

    // simple query scope
    //    public function scopeFilter($query) {
    //        if (request('search')) {
    //            $query
    //                ->where('title', 'like', '%' . request('search') . '%')
    //                ->orWhere('body', 'like', '%' . request('search') . '%');
    //        }
    //    }


    // will be rewritten in more professional way
    //    public function scopeFilter($query, array $filters) {
    //        if (isset($filters['search'])) {
    //            $query
    //                ->where('title', 'like', '%' . request('search') . '%')
    //                ->orWhere('body', 'like', '%' . request('search') . '%');
    //        }
    //    }


    public function scopeFilter($query, array $filters)
    {
        $query->when($filters['search'] ?? false, fn($query, $search) =>
            $query
                ->where('title', 'like', '%' . $search . '%')
                ->orWhere('body', 'like', '%' . $search . '%')
        );
    }


    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
