<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'category_id'
    ];

    // public $guarded = [];


    //to change the default route-model binding key
    //public function getRouteKeyName()
    //{
    // // return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
    // return 'slug';
    //}


    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }
}
